// PM2 Ecosystem Configuration - QuenBot
// Optimized for 12 vCPU (AMD) / 24 GB RAM
// Usage: pm2 start ecosystem.config.js
module.exports = {
  apps: [
    {
      name: "quenbot-api",
      cwd: "./artifacts/api-server",
      script: "npx",
      args: "tsx src/index.ts",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DATABASE_URL: process.env.DATABASE_URL || "postgres://user:password@localhost:5432/trade_intel",
        ADMIN_PIN: process.env.ADMIN_PIN || "BABA",
        UV_THREADPOOL_SIZE: "8",
        NODE_OPTIONS: "--max-old-space-size=2048",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "quenbot-agents",
      cwd: "./python_agents",
      script: "python3",
      args: "-O main.py",
      interpreter: "none",
      env: {
        PYTHONUNBUFFERED: "1",
        PYTHONOPTIMIZE: "1",
        DATABASE_URL: process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/trade_intel",
        DB_HOST: "localhost",
        DB_PORT: 5432,
        DB_USER: "user",
        DB_PASSWORD: "password",
        DB_NAME: "trade_intel",
        OLLAMA_NUM_PARALLEL: "2",
        OLLAMA_MAX_LOADED_MODELS: "2",
        QUENBOT_LLM_MODEL: "quenbot-brain",
        QUENBOT_LLM_NUM_CTX: "4096",
        QUENBOT_LLM_MAX_TOKENS: "384",
        QUENBOT_LLM_NUM_THREAD: "12",
        QUENBOT_CHAT_MODEL: "quenbot-brain",
        QUENBOT_ENABLE_CHAT_POLLER: "1",
        QUENBOT_CONTROL_TOKEN: process.env.QUENBOT_CONTROL_TOKEN || "",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "8G",
      error_file: "./logs/agents-error.log",
      out_file: "./logs/agents-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "quenbot-dashboard",
      cwd: "./dashboard",
      script: "bash",
      args: "-lc 'pnpm run start -- --hostname 0.0.0.0'",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        API_TARGET: "http://127.0.0.1:3001",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/dashboard-error.log",
      out_file: "./logs/dashboard-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
