// PM2 Ecosystem Configuration - QuenBot
// Optimized for 12 vCPU (AMD) / 24 GB RAM
// Usage: pm2 start ecosystem.config.js
const quenbotTimeZone = process.env.QUENBOT_TIMEZONE || "Europe/Vienna";

module.exports = {
  apps: [
    {
      name: "quenbot-api",
      cwd: "./artifacts/api-server",
      script: "npx",
      args: "tsx src/index.ts",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        TZ: quenbotTimeZone,
        QUENBOT_TIMEZONE: quenbotTimeZone,
        PORT: 3001,
        DATABASE_URL: process.env.DATABASE_URL || "postgres://user:password@localhost:5432/trade_intel",
        ADMIN_PIN: process.env.ADMIN_PIN || "BABA",
        UV_THREADPOOL_SIZE: "8",
        NODE_OPTIONS: "--max-old-space-size=2048",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: "30s",
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 15000,
      max_memory_restart: "2G",
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "quenbot-agents",
      cwd: "./python_agents",
      script: "python3",
      args: "-O main.py",
      interpreter: "none",
      env: {
        PYTHONUNBUFFERED: "1",
        PYTHONOPTIMIZE: "1",
        TZ: quenbotTimeZone,
        QUENBOT_TIMEZONE: quenbotTimeZone,
        DATABASE_URL: process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/trade_intel",
        DB_HOST: "localhost",
        DB_PORT: 5432,
        DB_USER: "user",
        DB_PASSWORD: "password",
        DB_NAME: "trade_intel",
        OLLAMA_NUM_PARALLEL: "2",
        OLLAMA_MAX_LOADED_MODELS: "2",
        QUENBOT_LLM_MODEL: "qwen3.5-coder:9b",
        QUENBOT_LLM_NUM_CTX: "4096",
        QUENBOT_LLM_MAX_TOKENS: "384",
        QUENBOT_LLM_NUM_THREAD: "12",
        QUENBOT_CHAT_MODEL: "qwen3.5-coder:9b",
        QUENBOT_DECISION_MODEL: "qwen3.5-coder:9b",
        QUENBOT_ENABLE_REDIS: process.env.QUENBOT_ENABLE_REDIS || "1",
        QUENBOT_REDIS_URL: process.env.QUENBOT_REDIS_URL || "redis://127.0.0.1:6379/0",
        QUENBOT_VECTOR_DB_PATH: process.env.QUENBOT_VECTOR_DB_PATH || "./.chroma",
        QUENBOT_USE_WS_CLIENT_BRIDGE: process.env.QUENBOT_USE_WS_CLIENT_BRIDGE || "0",
        QUENBOT_SCOUT_INGEST_WORKERS: process.env.QUENBOT_SCOUT_INGEST_WORKERS || "8",
        QUENBOT_SCOUT_TRADE_QUEUE_SIZE: process.env.QUENBOT_SCOUT_TRADE_QUEUE_SIZE || "50000",
        QUENBOT_SCOUT_TRADE_BATCH_SIZE: process.env.QUENBOT_SCOUT_TRADE_BATCH_SIZE || "96",
        QUENBOT_BINANCE_WS_MAX_QUEUE: process.env.QUENBOT_BINANCE_WS_MAX_QUEUE || "40000",
        QUENBOT_BYBIT_WS_MAX_QUEUE: process.env.QUENBOT_BYBIT_WS_MAX_QUEUE || "40000",
        QUENBOT_DISABLE_DRAWDOWN_GATE: process.env.QUENBOT_DISABLE_DRAWDOWN_GATE || "1",
        QUENBOT_ENABLE_CHAT_POLLER: "1",
        QUENBOT_CONTROL_TOKEN: process.env.QUENBOT_CONTROL_TOKEN || "",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: "30s",
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 20000,
      max_memory_restart: "12G",
      error_file: "./logs/agents-error.log",
      out_file: "./logs/agents-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "quenbot-dashboard",
      cwd: "./dashboard",
      script: "./node_modules/next/dist/bin/next",
      args: "start --port 5173 --hostname 0.0.0.0",
      env: {
        NODE_ENV: "production",
        TZ: quenbotTimeZone,
        QUENBOT_TIMEZONE: quenbotTimeZone,
        NEXT_PUBLIC_QUENBOT_TIMEZONE: quenbotTimeZone,
        PORT: 5173,
        HOSTNAME: "0.0.0.0",
        API_TARGET: "http://127.0.0.1:3001",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: "30s",
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 15000,
      max_memory_restart: "1G",
      error_file: "./logs/dashboard-error.log",
      out_file: "./logs/dashboard-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
