// PM2 Ecosystem Configuration - QuenBot
// Optimized for 12 vCPU (AMD) / 24 GB RAM
// Usage: pm2 start ecosystem.config.js
module.exports = {
  apps: [
    {
      name: "quenbot-api",
      cwd: "./artifacts/api-server",
      script: "npx",
      args: "tsx src/index.ts",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DATABASE_URL: process.env.DATABASE_URL || "postgres://user:password@localhost:5433/trade_intel",
        ADMIN_PIN: process.env.ADMIN_PIN || "BABA",
        UV_THREADPOOL_SIZE: "8",
        NODE_OPTIONS: "--max-old-space-size=2048",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "quenbot-agents",
      cwd: "./python_agents",
      script: "python3",
      args: "-O main.py",
      interpreter: "none",
      env: {
        PYTHONUNBUFFERED: "1",
        PYTHONOPTIMIZE: "1",
        DATABASE_URL: process.env.DATABASE_URL || "postgresql://user:password@localhost:5433/trade_intel",
        DB_HOST: "localhost",
        DB_PORT: 5433,
        DB_USER: "user",
        DB_PASSWORD: "password",
        DB_NAME: "trade_intel",
        OLLAMA_NUM_PARALLEL: "3",
        OLLAMA_MAX_LOADED_MODELS: "2",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "8G",
      error_file: "./logs/agents-error.log",
      out_file: "./logs/agents-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "quenbot-dashboard",
      cwd: "./artifacts/market-intel",
      script: "npx",
      args: "vite preview --port 5173 --host 0.0.0.0",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      error_file: "./logs/dashboard-error.log",
      out_file: "./logs/dashboard-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
